[package]
name = "multimap"
version = "0.3.0"
description = "A multimap implementation."
readme = "README.md"
repository = "https://github.com/havarnov/multimap"
license = "MIT/Apache-2.0"
authors = ["Håvar Nøvik <havar.novik@gmail.com>"]
documentation = "http://havarnov.github.io/multimap/multimap/index.html"

[features]
serde_impl = ["serde", "serde_derive"]
default = ["serde_impl"]

[dependencies]
serde = { version = "~1.0", optional = true }
serde_derive = { version = "~1.0", optional = true }
